import franBack from "../src/assets/SlidersList/franBack.svg";
import franAva from "../src/assets/SlidersList/franAva.svg";
import dot from "../src/assets/SlidersList/ellips.svg";

export const ItemData = [
  {
    id: 1,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
  {
    id: 2,
    img: franBack,
    title1: "24 May 2019",
    title2: "8 min read",
    desc: "How to design a product that can grow itself 10x in year:",
    userImg: franAva,
    userName: "Francesca Richards",
    dot: dot,
  },
];
